"""Firmware Generator Module - Generates platform-specific embedded firmware."""


class FirmwareGenerator:
    """Generates firmware for various microcontroller platforms."""

    SUPPORTED_PLATFORMS = {
        "esp32": "Arduino (ESP32)",
        "esp32-idf": "ESP-IDF",
        "stm32": "STM32 HAL",
        "stm32duino": "Arduino (STM32)",
        "arduino": "Arduino (AVR)",
        "rp2040": "Arduino (RP2040)",
        "rp2040-pico": "Pico SDK",
        "micropython": "MicroPython",
        "platformio": "PlatformIO",
    }

    def generate(self, spec: dict, components: list, connections: list, platform: str = "esp32") -> str:
        if platform in ("esp32", "esp32-idf"):
            return self._generate_esp32(spec, components, connections)
        elif platform in ("arduino", "stm32duino"):
            return self._generate_arduino(spec, components, connections)
        elif platform in ("rp2040", "rp2040-pico"):
            return self._generate_rp2040(spec, components, connections)
        elif platform == "micropython":
            return self._generate_micropython(spec, components, connections)
        elif platform in ("stm32",):
            return self._generate_stm32(spec, components, connections)
        return self._generate_esp32(spec, components, connections)

    def _generate_esp32(self, spec: dict, components: list, connections: list) -> str:
        sensors = spec.get("sensors", [])
        displays = spec.get("displays", [])
        interfaces = spec.get("interfaces", [])
        has_wifi = "WiFi" in interfaces or "wifi" in str(spec).lower()

        code = f'''/*
 * PCBMind AI - Auto-generated Firmware
 * Platform: ESP32
 * Project: {spec.get("project_name", "Hardware Project")}
 * Generated by PCBMind AI
 */

#include <Arduino.h>
#include <Wire.h>
'''

        if has_wifi:
            code += '''#include <WiFi.h>
#include <WebServer.h>
#include <ArduinoJson.h>
'''

        sensor_includes = {"BME280": "#include <Adafruit_BME280.h>",
                          "BMP280": "#include <Adafruit_BMP280.h>",
                          "MPU6050": "#include <MPU6050_tockn.h>",
                          "BH1750": "#include <BH1750.h>",
                          "DHT22": "#include <DHT.h>",
                          "MAX30102": "#include <MAX30105.h>"}
        display_includes = {"SSD1306": "#include <Adafruit_SSD1306.h>",
                           "ST7789": "#include <Adafruit_ST7789.h>"}

        for s in sensors:
            name = s.get("model", s.get("name", ""))
            for key, inc in sensor_includes.items():
                if key.lower() in name.lower():
                    code += inc + "\n"
        for d in displays:
            name = d.get("model", d.get("name", ""))
            for key, inc in display_includes.items():
                if key.lower() in name.lower():
                    code += inc + "\n"

        code += "\n// ===== PIN DEFINITIONS =====\n"
        for conn in connections:
            if conn.get("type") == "signal":
                pins = conn.get("pins", [])
                if len(pins) >= 2:
                    code += f"#define {conn['net_name'].replace(' ', '_').upper():30s} // {conn.get('description', '')}\n"

        code += "\n// ===== OBJECTS =====\n"
        for s in sensors:
            name = s.get("model", s.get("name", ""))
            var_name = name.lower().replace("-", "_").replace(" ", "_")
            if "bme280" in name.lower():
                code += f"Adafruit_BME280 {var_name};\n"
            elif "mpu6050" in name.lower():
                code += f"MPU6050_tockn {var_name}(Wire);\n"
            elif "bh1750" in name.lower():
                code += f"BH1750 {var_name};\n"
            elif "dht" in name.lower():
                code += f"DHT {var_name}(DHT_PIN, DHT_TYPE);\n"

        for d in displays:
            name = d.get("model", d.get("name", ""))
            if "ssd1306" in name.lower():
                code += "Adafruit_SSD1306 display(128, 64, &Wire, -1);\n"

        if has_wifi:
            code += '''
// ===== WiFi Configuration =====
const char* WIFI_SSID = "YOUR_WIFI_SSID";
const char* WIFI_PASS = "YOUR_WIFI_PASSWORD";
WebServer server(80);
'''

        code += f'''
// ===== SETUP =====
void setup() {{
    Serial.begin(115200);
    Serial.println("\\n=================================");
    Serial.println("  PCBMind AI - {spec.get('project_name', 'Hardware Project')}");
    Serial.println("=================================\\n");

    Wire.begin();
    Serial.println("[INIT] I2C bus initialized");

'''
        for s in sensors:
            name = s.get("model", s.get("name", ""))
            var_name = name.lower().replace("-", "_").replace(" ", "_")
            if any(k in name.lower() for k in ["bme280", "bmp280"]):
                code += f'    // Initialize {name}\n'
                code += f'    if (!{var_name}.begin(0x76)) {{\n'
                code += f'        Serial.println("[ERROR] {name} not found!");\n'
                code += f'    }} else {{\n'
                code += f'        Serial.println("[OK] {name} initialized");\n'
                code += f'    }}\n\n'
            elif "mpu6050" in name.lower():
                code += f'    {var_name}.begin();\n'
                code += f'    {var_name}.calcGyroOffsets(true);\n'
                code += f'    Serial.println("[OK] MPU6050 initialized");\n\n'
            elif "bh1750" in name.lower():
                code += f'    {var_name}.begin();\n'
                code += f'    Serial.println("[OK] BH1750 initialized");\n\n'

        for d in displays:
            name = d.get("model", d.get("name", ""))
            if "ssd1306" in name.lower():
                code += '''    // Initialize Display
    if(!display.begin(SSD1306_SWITCHCAPVCC, 0x3C)) {
        Serial.println("[ERROR] SSD1306 not found!");
    } else {
        display.clearDisplay();
        display.setTextSize(1);
        display.setTextColor(WHITE);
        display.setCursor(0, 0);
        display.println("PCBMind AI");
        display.println("Initializing...");
        display.display();
        Serial.println("[OK] Display initialized");
    }

'''

        if has_wifi:
            code += '''    // Connect to WiFi
    Serial.print("[WIFI] Connecting to ");
    Serial.println(WIFI_SSID);
    WiFi.begin(WIFI_SSID, WIFI_PASS);
    while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
    }
    Serial.println("\\n[WIFI] Connected!");
    Serial.print("[WIFI] IP Address: ");
    Serial.println(WiFi.localIP());

    // Setup web server routes
    server.on("/", HTTP_GET, handleRoot);
    server.on("/api/data", HTTP_GET, handleAPI);
    server.begin();
    Serial.println("[SERVER] HTTP server started");

'''

        code += '''    Serial.println("\\n[READY] System initialized successfully!\\n");
}

// ===== MAIN LOOP =====
void loop() {
'''
        if has_wifi:
            code += "    server.handleClient();\n"
            code += "    delay(2);\n"

        code += "\n    // Read sensors\n"
        code += "    unsigned long currentMillis = millis();\n"
        code += "    static unsigned long lastRead = 0;\n"
        code += "    const unsigned long READ_INTERVAL = 2000;\n\n"
        code += "    if (currentMillis - lastRead >= READ_INTERVAL) {\n"
        code += "        lastRead = currentMillis;\n\n"

        for s in sensors:
            name = s.get("model", s.get("name", ""))
            var_name = name.lower().replace("-", "_").replace(" ", "_")
            if "bme280" in name.lower():
                code += f"        float temperature = {var_name}.readTemperature();\n"
                code += f"        float humidity = {var_name}.readHumidity();\n"
                code += f"        float pressure = {var_name}.readPressure() / 100.0F;\n"
                code += '        Serial.printf("[DATA] Temp: %.1fC | Hum: %.1f%% | Press: %.1fhPa\\n",\n'
                code += "                  temperature, humidity, pressure);\n\n"
            elif "mpu6050" in name.lower():
                code += f"        {var_name}.update();\n"
                code += f"        float accelX = {var_name}.getAccelX();\n"
                code += f"        float accelY = {var_name}.getAccelY();\n"
                code += f"        float accelZ = {var_name}.getAccelZ();\n"
                code += '        Serial.printf("[DATA] Accel: X=%.2f Y=%.2f Z=%.2f\\n", accelX, accelY, accelZ);\n\n'
            elif "bh1750" in name.lower():
                code += f"        float lux = {var_name}.readLightLevel();\n"
                code += '        Serial.printf("[DATA] Light: %.1f lux\\n", lux);\n\n'

        for d in displays:
            name = d.get("model", d.get("name", ""))
            if "ssd1306" in name.lower():
                code += """        // Update display
        display.clearDisplay();
        display.setTextSize(1);
        display.setTextColor(WHITE);
        display.setCursor(0, 0);
        display.println("PCBMind AI - Sensor Data");
        display.println("----------------------");
        display.printf("Temp: %.1f C\\n", temperature);
        display.printf("Hum:  %.1f %%\\n", humidity);
        display.printf("Pres: %.1f hPa\\n", pressure);
        display.display();
"""
        code += "    }\n"
        code += "    delay(100);\n"
        code += "}\n"

        if has_wifi:
            code += '''
// ===== WEB SERVER HANDLERS =====
void handleRoot() {
    String html = "<!DOCTYPE html><html><head><title>PCBMind AI</title>";
    html += "<meta name='viewport' content='width=device-width,initial-scale=1'>";
    html += "<style>body{font-family:monospace;background:#1a1a2e;color:#fff;padding:20px;}";
    html += "h1{color:#4a9eff;} .data{background:#16213e;padding:15px;border-radius:8px;margin:10px 0;}</style></head>";
    html += "<body><h1>PCBMind AI - Sensor Dashboard</h1>";
    html += "<div class='data'><p>Loading data...</p></div>";
    html += "<script>setInterval(()=>{fetch('/api/data').then(r=>r.json()).then(d=>{";
    html += "document.querySelector('.data').innerHTML=Object.entries(d).map(([k,v])=>";
    html += "`<p><b>${k}:</b> ${v}</p>`).join('');});},2000);</script>";
    html += "</body></html>";
    server.send(200, "text/html", html);
}

void handleAPI() {
    StaticJsonDocument<256> doc;
    doc["status"] = "ok";
    doc["uptime"] = millis() / 1000;
    doc["ip"] = WiFi.localIP().toString();
    String response;
    serializeJson(doc, response);
    server.send(200, "application/json", response);
}
'''
        return code

    def _generate_arduino(self, spec: dict, components: list, connections: list) -> str:
        return self._generate_esp32(spec, components, connections).replace("ESP32", "Arduino")

    def _generate_rp2040(self, spec: dict, components: list, connections: list) -> str:
        return self._generate_esp32(spec, components, connections).replace("ESP32", "RP2040")

    def _generate_micropython(self, spec: dict, components: list, connections: list) -> str:
        sensors = spec.get("sensors", [])
        code = f'''"""
PCBMind AI - Auto-generated MicroPython Firmware
Project: {spec.get("project_name", "Hardware Project")}
Platform: MicroPython (ESP32/RP2040)
"""

import time
import machine
from machine import Pin, I2C

print("\\n=================================")
print("  PCBMind AI - {spec.get('project_name', 'Hardware Project')}")
print("=================================\\n")

# I2C Setup
i2c = I2C(0, scl=Pin(22), sda=Pin(21), freq=400000)
print("[INIT] I2C devices found:", i2c.scan())

'''
        for s in sensors:
            name = s.get("model", s.get("name", ""))
            if "bme280" in name.lower():
                code += '''# BME280 Sensor
class BME280:
    def __init__(self, i2c, addr=0x76):
        self.i2c = i2c
        self.addr = addr
        self.i2c.writeto(self.addr, bytes([0xF2, 0x27]))
        self.i2c.writeto(self.addr, bytes([0xF4, 0x27]))

    def read_temperature(self):
        data = self.i2c.readfrom(self.addr, 3)
        return ((data[0] << 8 | data[1]) >> 4) * 0.01

    def read_humidity(self):
        data = self.i2c.readfrom(self.addr, 2)
        return (data[0] << 8 | data[1]) / 1024.0

    def read_pressure(self):
        data = self.i2c.readfrom(self.addr, 3)
        return ((data[0] << 16 | data[1] << 8 | data[2]) >> 4) / 256.0 / 100.0

bme = BME280(i2c)
print("[OK] BME280 initialized")

'''
        code += '''
# Main Loop
while True:
    try:
'''
        for s in sensors:
            name = s.get("model", s.get("name", ""))
            if "bme280" in name.lower():
                code += """        temp = bme.read_temperature()
        hum = bme.read_humidity()
        pres = bme.read_pressure()
        print(f"[DATA] Temp: {temp:.1f}C | Hum: {hum:.1f}% | Press: {pres:.1f}hPa")
"""
        code += """    except Exception as e:
        print(f"[ERROR] {e}")

    time.sleep(2)
"""
        return code

    def _generate_stm32(self, spec: dict, components: list, connections: list) -> str:
        return f'''/*
 * PCBMind AI - STM32 HAL Firmware
 * Project: {spec.get("project_name", "Hardware Project")}
 * Platform: STM32 HAL
 */

#include "stm32f1xx_hal.h"
#include <stdio.h>

UART_HandleTypeDef huart2;

void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);

int main(void) {{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART2_UART_Init();

    printf("\\nPCBMind AI - {spec.get('project_name', 'Project')}\\n");
    printf("STM32 HAL Firmware\\n\\n");

    while (1) {{
        HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
        HAL_Delay(1000);
    }}
}}

void SystemClock_Config(void) {{}}
static void MX_GPIO_Init(void) {{}}
static void MX_USART2_UART_Init(void) {{}}
'''
