class GerberGenerator:
    """Generates Gerber files from project PCB data."""

    def generate(self, project) -> dict[str, str]:
        pcb_data = project.pcb_data or {}
        board = pcb_data.get("board", {})
        width = board.get("width_mm", 80)
        height = board.get("height_mm", 60)

        files = {}

        files[f"{project.name}.GTL"] = self._generate_copper_layer(pcb_data, "F.Cu", width, height)
        files[f"{project.name}.GBL"] = self._generate_copper_layer(pcb_data, "B.Cu", width, height)
        files[f"{project.name}.GTS"] = self._generate_solder_mask(pcb_data, "F.Mask", width, height)
        files[f"{project.name}.GBS"] = self._generate_solder_mask(pcb_data, "B.Mask", width, height)
        files[f"{project.name}.GTO"] = self._generate_silkscreen(pcb_data, "F.SilkS", width, height)
        files[f"{project.name}.GBO"] = self._generate_silkscreen(pcb_data, "B.SilkS", width, height)
        files[f"{project.name}.GKO"] = self._generate_board_outline(width, height)
        files[f"{project.name}.DRL"] = self._generate_drill_file(pcb_data)

        return files

    def _generate_copper_layer(self, pcb_data, layer_name, width, height):
        lines = [
            f"G04 PCBMind AI - {layer_name} Copper Layer*",
            f"G04 Generated for: PCB Design*",
            "%FSLAX46Y46*%",
            "%MOIN*%",
            "%ADD10C,0.010000*%",
            "%ADD11R,0.010000 X0.010000*%",
            "D10*",
        ]

        lines.append(f"G04 Board Outline*")
        lines.append("X0Y0D02*")
        lines.append(f"X{int(width * 100000)}Y0D02*")
        lines.append(f"X{int(width * 100000)}Y{int(height * 100000)}D02*")
        lines.append(f"X0Y{int(height * 100000)}D02*")
        lines.append("X0Y0D02*")

        components = pcb_data.get("components", [])
        for comp in components:
            x = comp.get("x", 0)
            y = comp.get("y", 0)
            lines.append(f"G04 Component: {comp.get('id', 'U?')}*")
            lines.append(f"X{int(x * 100000)}Y{int(y * 100000)}D02*")

        tracks = pcb_data.get("tracks", [])
        for track in tracks:
            start = track.get("start", {})
            end = track.get("end", {})
            lines.append(f"G04 Track: {track.get('net', '')}*")
            lines.append(f"X{int(start.get('x', 0) * 100000)}Y{int(start.get('y', 0) * 100000)}D02*")
            lines.append(f"X{int(end.get('x', 0) * 100000)}Y{int(end.get('y', 0) * 100000)}D01*")

        lines.append("M02*")
        return '\n'.join(lines)

    def _generate_solder_mask(self, pcb_data, layer_name, width, height):
        return (
            f"G04 PCBMind AI - {layer_name} Solder Mask*\n"
            f"%FSLAX46Y46*%\n"
            f"%MOIN*%\n"
            f"G04 Board: {width}mm x {height}mm*\n"
            "M02*"
        )

    def _generate_silkscreen(self, pcb_data, layer_name, width, height):
        components = pcb_data.get("components", [])
        lines = [
            f"G04 PCBMind AI - {layer_name} Silkscreen*",
            "%FSLAX46Y46*%",
            "%MOIN*%",
        ]
        for comp in components:
            ref = comp.get("id", "")
            x = comp.get("x", 0)
            y = comp.get("y", 0)
            lines.append(f"G04 Silkscreen: {ref} at ({x}, {y})*")
        lines.append("M02*")
        return '\n'.join(lines)

    def _generate_board_outline(self, width, height):
        return (
            f"G04 PCBMind AI - Board Outline*\n"
            "%FSLAX46Y46*%\n"
            "%MOIN*%\n"
            "D44*\n"
            f"X0Y0D02*\n"
            f"X{int(width * 100000)}Y0D01*\n"
            f"X{int(width * 100000)}Y{int(height * 100000)}D01*\n"
            f"X0Y{int(height * 100000)}D01*\n"
            f"X0Y0D01*\n"
            "M02*"
        )

    def _generate_drill_file(self, pcb_data):
        components = pcb_data.get("components", [])
        lines = [
            "M48",
            ";DRILL FILE - Generated by PCBMind AI",
            "FMAT,2",
            "METRIC,TZ",
            "T1C0.300000",
        ]
        for i, comp in enumerate(components):
            x = comp.get("x", 0)
            y = comp.get("y", 0)
            lines.append(f"T1")
            lines.append(f"X{x:.3f}Y{y:.3f}")
        lines.append("T0")
        lines.append("M30")
        return '\n'.join(lines)
