class STEPGenerator:
    """Generates simplified 3D STEP model data for PCB visualization."""

    def generate_board_model(self, project) -> dict:
        pcb_data = project.pcb_data or {}
        board = pcb_data.get("board", {})
        width = board.get("width_mm", 80)
        height = board.get("height_mm", 60)
        thickness = board.get("thickness_mm", 1.6)

        components = pcb_data.get("components", [])

        model = {
            "board": {
                "shape": "box",
                "dimensions": {
                    "width": width,
                    "height": height,
                    "thickness": thickness,
                },
                "material": {
                    "name": "FR4",
                    "color": "#2d5a27",
                    "opacity": 1.0,
                },
            },
            "copper_layers": [
                {
                    "name": "F.Cu",
                    "z_offset": thickness / 2 - 0.035,
                    "thickness": 0.035,
                    "color": "#cc7722",
                },
                {
                    "name": "B.Cu",
                    "z_offset": -thickness / 2,
                    "thickness": 0.035,
                    "color": "#cc7722",
                },
            ],
            "solder_mask": [
                {"name": "F.Mask", "z_offset": thickness / 2, "color": "#006633", "opacity": 0.8},
                {"name": "B.Mask", "z_offset": -thickness / 2, "color": "#006633", "opacity": 0.8},
            ],
            "silkscreen": [
                {"name": "F.SilkS", "z_offset": thickness / 2 + 0.01, "color": "#ffffff"},
            ],
            "components_3d": [],
        }

        for comp in components:
            model["components_3d"].append({
                "id": comp.get("id", ""),
                "position": {
                    "x": comp.get("x", 0),
                    "y": comp.get("y", 0),
                    "z": thickness / 2 + 0.5,
                },
                "rotation": comp.get("rotation", 0),
                "layer": comp.get("layer", "F.Cu"),
                "package": comp.get("footprint", "SMD"),
                "color": "#1a1a1a",
            })

        return model

    def generate_step_header(self, project) -> str:
        return f"""ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('PCB Model generated by PCBMind AI'),'2;1');
FILE_NAME('{project.name}','2024-01-01',('PCBMind AI'),('PCBMind AI'),'','','');
FILE_SCHEMA(('AUTOMOTIVE_DESIGN'));
ENDSEC;
DATA;
ENDSEC;
END-ISO-10303-21;"""
