class WiringDiagramGenerator:
    """Generates text-based wiring diagrams."""

    def generate(self, project) -> str:
        components = project.components or []
        connections = project.connections or []

        lines = [
            f"# Wiring Diagram: {project.name}",
            f"## Generated by PCBMind AI",
            "",
            "## Component Connections",
            "",
        ]

        by_component = {}
        for conn in connections:
            for pin in conn.get("pins", []):
                comp = pin.get("component", "")
                if comp not in by_component:
                    by_component[comp] = []
                by_component[comp].append({
                    "pin": pin.get("pin", ""),
                    "net": conn.get("net_name", ""),
                    "type": conn.get("type", "signal"),
                })

        for comp_name, pins in by_component.items():
            lines.append(f"### {comp_name}")
            lines.append("| Pin | Net | Type |")
            lines.append("|-----|-----|------|")
            for pin in pins:
                lines.append(f"| {pin['pin']} | {pin['net']} | {pin['type']} |")
            lines.append("")

        lines.append("## Power Distribution")
        lines.append("```")
        lines.append("USB 5V ──┬── [Schottky Diode SS14] ──┬── VIN")
        lines.append("          │                            │")
        lines.append("          │                      [AMS1117-3.3]")
        lines.append("          │                            │")
        lines.append("          │                         3.3V Rail")
        lines.append("          │                     ┌──────┼──────┐")
        lines.append("          │                   [100nF] [10uF]  [100nF]")
        lines.append("          │                     │      │      │")
        lines.append("          │                    VCC    VCC    VCC")
        lines.append("          │")
        lines.append("         GND ──────────────────────────────────")
        lines.append("```")
        lines.append("")

        lines.append("## I2C Bus")
        lines.append("```")
        lines.append("ESP32 GPIO21 (SDA) ──┬── 4.7K ── 3.3V")
        lines.append("                     ├── BME280 SDA")
        lines.append("                     └── OLED SDA")
        lines.append("")
        lines.append("ESP32 GPIO22 (SCL) ──┬── 4.7K ── 3.3V")
        lines.append("                     ├── BME280 SCL")
        lines.append("                     └── OLED SCL")
        lines.append("```")
        lines.append("")

        lines.append("## Status LED")
        lines.append("```")
        lines.append("ESP32 GPIO4 ──── 1K Resistor ──── LED (Anode)")
        lines.append("                                      │")
        lines.append("                                     GND")
        lines.append("```")

        return '\n'.join(lines)
